# This file is machine-generated - editing it directly is not advised

[[Waveforms]]
git-tree-sha1 = "532113cb46e2da7019672f7879b97ada3edd3dc6"
uuid = "cb13b1c6-351e-5134-b3ad-d6a530956a82"
version = "0.1.1"
